"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['tided02.py']
DATA_FILES = ['/Users/salmoni/Projects/TiDEd/Resources/TiDEd.icns'] # --iconfile
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/salmoni/Projects/TiDEd/Resources/TiDEd.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
